# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mental Work
email: info@mentalwork.net
description: >- # this means to ignore newlines until "baseurl:"
  Neural interfaces are information technology systems that interact directly with the human nervous system to control a computer, machine or connect to the internet. They can be non-invasive, picking up signals through electrodes placed outside the body, or invasive, breaking the skin or skull barrier to implant electrodes directly into the brain or peripheral nervous system.
  The Mental Work Research Platform offers a unique opportunity to explore the myriad possibilities of designing and testing new neural interfaces by creating user-centric models for neural interfaces based on user experience design. The overarching research direction is to explore how different neural interface designs can enhance a feeling of embodiment in the user: How can we improve on the sense of “being part of the machine” to augment control? Equally important is an empirical exploration of the ethical concerns that neural interfaces evoke. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mentalwork.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
